#
#
version: '3'

networks:
  kiva-network:
    external: true

services:

  besu-node1:
    build: ./
    image: besu-node
    container_name: besu-node
    working_dir: /app
    ports:
      - 8545:8545     # JSON-RPC over HTTP
      - 8546:8546     # JSON-RPC over WebSockets
      - 8547:8547     # GraphQL over HTTP
      - 30303:30303   # P2P port
    expose:
      - "8545"
      - "8546"
      - "8547"
      - "30303"
    networks:
      kiva-network:
        ipv4_address: 10.0.0.99
